spring:
  redis:
    host: localhost
    port: 6379
  profile:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587 #587 -> encryption 25 -> non encryption
    userName: chandrakarnehil@gmail.com
    password: ofnm pqfs oqyg nivb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    net:
      journalingN:
        journaling: DEBUG
weather:
  api:
    key: bee18230329797d9203c5757213540f3



